### ISSUE TITLE
Remove dash-line of «add stops» when dragging a stop

### ISSUE THREAD

**Issue by qchasserieau** [systragroup/quetzal-network-editor#100]
Quand on cherche à déplacer un nœud, on a encore la ligne pointillée de la prolongation

**Comment by siforf564** [comment]
Il faudrait que le layer dash-line soit placé sous celui des nodes aussi

**Comment by sboivinsystra** [comment]
Je vais essayer de placer la desactivation de la ligne pointillé sur un mouseDown, mouseUP comme pour le déplacement des noeds. en ce moment il est seulement désactiver lorsquon est en mouseOn sur les noeds et liens, avec unpeu de lag ca ne fonctionne pas bien pour le déplacement des noeds

**Comment by sboivinsystra** [comment]
j'ai pas reussi pour la position du dashline
