### ISSUE TITLE
Propositions amélioration ergonomie

### ISSUE THREAD

**Issue by dllaborde** [systragroup/quetzal-network-editor#114]
Bonjour l'équipe,

Top votre projet ;). Ci-dessous quelques suggestions d'améliorations :
- le composant pour fermer le panneau des lignes se détache du panneau 
![image](https://user-images.githubusercontent.com/104993184/191760279-00dbcf14-47d8-43f5-a3d3-948d01ea1bb6.png)
- Fixer une valeur minimale pour le panneau des lignes  (sachant qu'on peut le rabattre) qui permette d'avoir une lisibilité d'un nombre standard de caractères pour une ligne (avec mon zoom par défaut à 100% j'avais les deux premières lignes qui s'appellent "STM_10..." 
![image](https://user-images.githubusercontent.com/104993184/191760682-d2314168-31d1-4ab1-9a51-fa3728341c9f.png)

- Eventuellement grossir un peu le header "Ligne" et mettre un oeil sur le bandeau vert qui permette de faire l'action "Cacher tout" " Montrer tout" quitte à mettre un tooltip si pas suffisament clair ? ça permet de s'éviter deux boutons en bas (surtout quand on édite on se retrouve avec 4 boutons en bas). Et aussi mettre "Lignes" au pluriel
![image](https://user-images.githubusercontent.com/104993184/191762807-acdf8272-1f75-40c8-826a-6799d3492a27.png)

- Au niveau des boutons d'actions, avoir une cohérence des boutons (ils sont différents là entre dans le formulaire du tableau de la ligne, et les 4 boutons en dessous du panneau). En général on met en avant l'action principale dans une couleur principale, et l'autre dans un couleur secondaire comme ci-dessous (éventuellement tester si mettre le bouton secondaire comme vous l'avez mis actuellement sans aplat de couleur sauf quand on le survole)

![image](https://user-images.githubusercontent.com/104993184/191766338-ba9545b4-3d94-41f2-892c-5c9331c2ceed.png)

- Mettre les boutons plus à droite sous le formulaire du panneau, et dans l'ordre "annuler" / "valider" (vu qu'on s'attend plutôt à ce que l'action principale soit valider" 

![image](https://user-images.githubusercontent.com/104993184/191769545-95dbe81b-52dd-4a5f-b969-ff285070392d.png)

- Garder la couleur rouge pour une alerte. Je ne suis pas sûre que ce soit nécessaire de mettre le crayon en rouge (ou même l'annuler en rouge, si jamais le "valider" a été plus mis en valeur). Peut être laisser le bouton crayon en noir lorsque l'on est en train d'éditer (sachant que les autres vont rester disabled. Idem pas sûr que ce soit nécessaire de mettre la poubelle en rouge, sachant que vous avez mis une pop up pour alerter en cas d'erreur. (dans une appli on avait joué sur le code couleur d'un crayon mais il y avait un process : rouge pour formulaire vide, orange pour formulaire entamé, vert quand formulaire validé)

- J'ai mis du temps à trouver le bouton "exporter" qui est tout en bas de l'onglet, je me demande si ça devrait pas plutôt être à un autre endroit. 2 possibilités, juste en dessous du plan (comme ça, ça fait "importer / plan / exporter" à la suite, ou bien en haut à droite du panneau lignes

![image](https://user-images.githubusercontent.com/104993184/191768055-fe4e6631-bbae-4ae5-af79-b136b79c1277.png)

- Quand l'oeil est masqué, utiliser la couleur grise (plutôt que le noir)
![image](https://user-images.githubusercontent.com/104993184/191770325-d5b7b421-9310-4a77-a1b5-a218d212cfaa.png)

A dispo si vous voulez échanger sur ces propositions (et aucune obligation de les prendre en compte bien sûr !)

**Comment by sboivinsystra** [comment]
oui merci beaucoup @dllaborde !, je vais integrer tes suggestions (que j'ai la capacité de faire) dans le prochain release, je ferais des issues avec le reste.

ca look bien maintenant!

![Screen Shot 2022-10-03 at 4 32 15 PM](https://user-images.githubusercontent.com/79281989/193676793-1d2553f4-c17d-428e-8eba-b45ec1ebb1c3.png)

**Comment by dllaborde** [comment]
Top @sboivinsystra  que tu aies pu intégrer déjà des retours ! @siforf564 je vais en parler à Arnaud pour voir comment on peut vous appuyer sur le sujet VUE/CSS, je te tiens au courant.

**Comment by sboivinsystra** [comment]
tout a été ajouté ou le sera dans la prochaine release. Seul la longeur en fonction du nombre de caracteres n'a pas été implémenté pour ne pas avoir un sidePanel trop large.
