### ISSUE TITLE
 fusion des reseaux : gerer les conflits

### ISSUE THREAD

**Issue by qchasserieau** [systragroup/quetzal-network-editor#127]
on pourrait avoir un bouton d'upload toujours accessible qui permet d'ajouter un zip / des geojsons et les fusionner à ceux qu'on a déjà.

1 vérifier s'il y a un conflit sur les indexs des liens et des nœuds
2 ouvrir une boite de dialogue 
- qui dit s'il y a des conflits et 
- proposer (imposer le cas échéant) de choisir des suffixes pour les indexs des deux tables
- proposer l'ajout d'une colonne pour les lignes (et les nœuds ?) avec des valeurs 
La colonne pourra être utilisée pour des tris dans l'affichage ensuite

Les liens et les nœuds sont concaténés en conservant toutes les colonnes des deux tables.

**Comment by sboivinsystra** [comment]
dans import.vue.  wrappé autour de la function loadNetwork() me semble l'endroit ideal.

tout fichiers loadé dans l'app passe par cette fonction. on peut regarder si les indices sont dupliqué des reseaux.
if not duplicated : go on and import
if duplicated: give choices (create new index from 0. create new random indexes for new files, etc).

Then change the files. then recheck.

**Comment by qchasserieau** [comment]
lancer action quand un réseau link + nodes est chargé alors qu'un réseau est déjà présent dans l'app 

action : 

1. test index noeuds -> **no conflict** ou **conflict**
2. si conflit : tester correspondence avec les hash-> **perfect_match** ou **no_match**
3. si **no_match** 

Dans l'import de PT network : 
Si aucun index dupliqué : GOOD

Lignes : 
key : default no
if yes ask for two keys for app and uploaded network
add a column with the keys in the links

Nodes : 
perfect match only
Duplicate distant dones

**Comment by sboivinsystra** [comment]
perfect match for dist <10 (1meters was really nothing)
