### ISSUE TITLE
Uniformiser les icônes upload et dowload

### ISSUE THREAD

**Issue by qchasserieau** [systragroup/quetzal-network-editor#128]
fa-duotone fa-download
fa-duotone fa-upload
par exemple

**Comment by sboivinsystra** [comment]
@qchasserieau  cest pas gratuit les duotone

**Comment by siforf564** [comment]
fa-solid fa-upload
![image](https://user-images.githubusercontent.com/56046851/196257441-1c322c44-1e5a-436f-965b-bae7a1d3be64.png)
