### ISSUE TITLE
Set up translation for German, Portuguese and Spanish

### ISSUE THREAD

**Issue by qchasserieau** [systragroup/quetzal-network-editor#147]
En ajoutant les langues aux langues disponibles et en créant la structure de fichier.
Je ferai PT et ES, marlin l'allemand.

BTW, ça m'a pas l'air easy easy à maintenir la structure où toutes les langues sont des fichiers séparés mais c'est pas un design maison j'imagine.

**Comment by sboivinsystra** [comment]
je crois que cest facile. la on a un fichier de traduction dans le dossier fr. j'imagine quil y en aura dautres...
src/locale/fr/

par contre, cest compliqé si il faut que des 3 personnes viennt faire la traductions avant chaque release

**Comment by qchasserieau** [comment]
ouais, ça semblait pas compliqué.
Yavait aussi une affaire de «langues disponibles» dans un fichier de config il me semble mais effectivement c'est pas bien compliqué.

Oui, ça peut devenir lourd mais quand tu sais que t'as à le faire, n'importe qui d'autorisé peux l'éditer tranquillement depuis github quand tu vois que la traduction déconne. pis c'est intégré à la prochaine release

C'est juste un flex anyway

**Comment by sboivinsystra** [comment]
depuis github plus ou moins. les fichiers sont generé avec une commande et ils sont compilé avec une autre commande (pour le release). alors oui, si je compile (genere le fichier) tu peux l'éditer dans github et apres je le compile et release
