### ISSUE TITLE
import a big network

### ISSUE THREAD

**Issue by qchasserieau** [systragroup/quetzal-network-editor#153]
Like all the mf buses of Germany
https://github.com/marlinarnz/quetzal_germany/blob/master/model/base/de_pt_network_agg/links.geojson

**Comment by sboivinsystra** [comment]
et ca ne fonctionne pas?

**Comment by sboivinsystra** [comment]
ajouter des verifs a l'import.

les liens manque tout. trip_id, a, b et le crs

**Comment by sboivinsystra** [comment]
I think large network are supported now. it should run even faster on the next release (V3.0).
