### ISSUE TITLE
Revoir le styling des liens 'hidden'

### ISSUE THREAD

**Issue by siforf564** [systragroup/quetzal-network-editor#155]
Quand on regarde un gros réseau, la fonction de hide ne fonctionne pas très bien:
![image](https://user-images.githubusercontent.com/56046851/198376726-15a50a72-d290-43aa-b9b9-8d3635c9811e.png)

2 choix:
- Retirer complètement de la carte les links hidden
- Avoir une transparence sur la couche entière, non par lien

**Comment by qchasserieau** [comment]
The hidden links and nodes should not be rendered.
