### ISSUE TITLE
add scale + link length

### ISSUE THREAD

**Issue by RobinGoix** [systragroup/quetzal-network-editor#176]
It is hard to estimate distances when editing links, especially when starting from scratch. I would recommend two changes:
- add scalebar in one edge of the map
- add the length of the link in edit mode when creating a new one (see attached picture)
![image](https://user-images.githubusercontent.com/7251843/201684618-824f2eee-eace-4d5d-bd8e-ff649e6c9e53.png)

**Comment by sboivinsystra** [comment]
Thank you for the input!

I will add the scaleBar in the next release. adding dynamic text on the map could be difficult tho. We could try in the future if it become a must have, but right now it will go into the backlog.

![Screenshot 2022-11-18 at 5 23 00 PM](https://user-images.githubusercontent.com/79281989/202813024-d96b0a7a-dd6b-4759-8b3c-d0368e224d22.png)
