### ISSUE TITLE
Creating wrong outputs / import error

### ISSUE THREAD

**Issue by RobinGoix** [systragroup/quetzal-network-editor#177]
[output (7).zip](https://github.com/systragroup/quetzal-network-editor/files/10004625/output.7.zip)

I just created this attached simple network with one route and one trip with quenedi.
I cannot load it anymore as I get the below error:
![image](https://user-images.githubusercontent.com/7251843/201703699-04cfd456-f183-4810-a10d-45c0ad707aa3.png)

The content seems correct as I could open it with both QGis and Geopandas.

I tried creating several times simple network like this one and got this error a few times, without noticing specific action from my side triggering this error.

**Comment by sboivinsystra** [comment]
thank you Robin I'll check into that. It will fit well into the next milestone wich was basically making sure the import works and  or tell if there is a problem.
