### ISSUE TITLE
Specify Types for standard attributes

### ISSUE THREAD

**Issue by siforf564** [systragroup/quetzal-network-editor#200]
E.G. Headway, Time, Length, hape_dist_traveled = Float

**Comment by siforf564** [comment]
index, a, b, trip_id, route_id, agency_id, route_long_name, route_short_name, route_type = str
length, time, headway, route_width = float
pichup_type, drop_off_type, link_sequence, direction_id = int

**Comment by sboivinsystra** [comment]
if you import a network with String in a Number field, it will become nan...

also, there is no 'int' in javascript... if i round it will still export as a float
