### ISSUE TITLE
Le projet ne charge pas avec importer -> load links + load nodes

### ISSUE THREAD

**Issue by qchasserieau** [systragroup/quetzal-network-editor#212]
![image](https://user-images.githubusercontent.com/32388980/218583500-f4274f12-2e27-42c4-b7c6-22e9db224e22.png)
L'application reste figée avec les deux fichiers chargés, tout vert, pas d'erreur mais ça ne se lance pas

**Comment by sboivinsystra** [comment]
question:
1) en chargeant des PT ou des Road links? (le road nest pas supporté sur cette page)
2) en utilisant le zip ou les fichiers individuelles?

**Comment by qchasserieau** [comment]
fichiers individuels road

**Comment by sboivinsystra** [comment]
roads not yet supported in this page. this page will be merge with "new project" in next release anyway
