### ISSUE TITLE
remove road node popup or offer option to select the column to display

### ISSUE THREAD

**Issue by qchasserieau** [systragroup/quetzal-network-editor#224]

**Comment by sboivinsystra** [comment]
je crois que c'est un bug. il n'y a pas de node popup.

**Comment by qchasserieau** [comment]
J'ai du mal à prendre une capture car c'est un popup :
Quand je suis sur un nœud routier en édition routier, il se met en gros avec une popup [undefined]. Oui, ça à l'air d'un bug.
Mais quand je mets le popup routier à None, le popup node disparait aussi
