### ISSUE TITLE
Add traffic times based on a microservice

### ISSUE THREAD

**Issue by qchasserieau** [systragroup/quetzal-network-editor#226]
An API can map the times of a distance matrix on the network

**Comment by sboivinsystra** [comment]
rapport (png) + matrice + temps / vitesse sur le reseau

**Comment by sboivinsystra** [comment]
possiblement: nouvelle page (conteur de vitesse ou cerveau).
1) apiKey en input dans le front [pour commencer

**Comment by sboivinsystra** [comment]
fas fa-tachometer-alt

**Comment by sboivinsystra** [comment]
TODO: remove listBucket from policy, delete after some time or delete with front (like osm)

**Comment by sboivinsystra** [comment]
![image](https://github.com/systragroup/quetzal-network-editor/assets/79281989/94dc8a64-f0d0-4b75-9a43-44c7927cfbdc)

**Comment by sboivinsystra** [comment]
![image](https://github.com/systragroup/quetzal-network-editor/assets/79281989/3941a568-eb15-4195-99f7-173c6647da5a)

**Comment by sboivinsystra** [comment]
j'ai ajouté une verification du datetime. (regex) il n'y a pas vraiment de selecteur de datetime avec vuetify.
