### ISSUE TITLE
pictures are ugly in the results 

### ISSUE THREAD

**Issue by qchasserieau** [systragroup/quetzal-network-editor#252]

**Comment by qchasserieau** [comment]
![image](https://user-images.githubusercontent.com/32388980/224148544-76866686-a5a5-425b-aa46-3fdfc058e7e0.png)
Quand on zoom : les images deviennent petites.
On souhaite que quand les images sont dans des sous dossiers, l'arborescence des dossiers se retrouve dans la page de résultat

**Comment by sboivinsystra** [comment]
j'ai fait des correctif. 
Il faudrait définir ce qu'on veut. si il y a des sous-dossier, est-ce qu'on veut avoir une liste d'image et seulement afficher une image à la fois?
