### ISSUE TITLE
Make use of authenfication in API Gateway

### ISSUE THREAD

**Issue by siforf564** [systragroup/quetzal-network-editor#269]
Use cognito auth to interact with api gateway.

**Comment by siforf564** [comment]
I think we have no choices but using Lambda auth in API gatweay to do this

**Comment by sboivinsystra** [comment]
Lambda auth for cognito cannot work as only the header in passed. As we want to check that the request body match the Auth. we connot use that.

My solution is a Auth step in each Step function. Calling a lambda function that get pass the Auth token and the payload. and check that the token has the correct access for the S3 bucket for this given model.

This auth lambda function should be added as the first step of each Step function definition.

**Comment by sboivinsystra** [comment]
could pass the header to the step function (instead of providing it in the body). but this would make the auth step necessary as the event object would have body and head keys

https://kennbrodhagen.net/2015/12/02/how-to-access-http-headers-using-aws-api-gateway-and-lambda/
