### ISSUE TITLE
add access to run logs files via launcher

### ISSUE THREAD

**Issue by qchasserieau** [systragroup/quetzal-network-editor#299]

**Comment by sboivinsystra** [comment]
1) Lambda lance un notebook avec des sorties qui sont capturé
2) écrire ces sorties sur S3 (log.txt)
3) dans le front. bouton @click = downloadLog() apres une exec.

**Comment by sboivinsystra** [comment]
5.3.b
quetzal main.py docker function was also updated to export logs into logs/ folder.
