### ISSUE TITLE
Two-direction field edition in road link edition

### ISSUE THREAD

**Issue by qchasserieau** [systragroup/quetzal-network-editor#330]
L’interface est déjà prévue pour représenter des voie à double sens (oneway=False)
Pour ces voies là on souhaiterait pouvoir editer les champs (vitesse, voies, bandes cyclables) pour les deux directions de façon ergonomique. 
par exemple avec les deux valeurs côte à côte dans le formulaire.
En interne pour stocker la valeur et pour l’export on peut utiliser un suffixe _r pour les champs de la direction retour.
Le suffixe fonctionne deja avec la version actuelle mais le côté à côté permettrait une meilleure ergonomie et voir directement quels champs sont directionnel et lesquels sont partagés.
Dans tous les cas, les réseaux routiers à géométries unique vont à mon avis devenir standard pour l’édition.
Il sont dédoublés a l’import dans quetzal et restent aussi doubles pour les cartes de charge.

**Comment by sboivinsystra** [comment]
je ne suis pas certain de la methode pour les liens a geometrie unique (oneway=False). 
est-ce qu'on parle d'avoir les rlinks et rlinks_r dans le geojson et seulement afficher les links?
aussi, dans tous les cas, c'est difficile de savoir que liens représente quel direction lors de l'édition. on pourrait seulement afficher un des deux liens selon l'emplacement de la souris dans le formulaire...

**Comment by sboivinsystra** [comment]
j'ai ça pour l'instant.  comme mentionné plus haut, impossibe de savoir quel lien est quel direction

![image](https://user-images.githubusercontent.com/79281989/235228409-4e811b94-4198-4cf6-aef7-340ac64dbab0.png)

**Comment by sboivinsystra** [comment]
Added some arrow (from node a to b of each selected links)

![image](https://user-images.githubusercontent.com/79281989/235239001-37075d3d-1959-4302-bc43-2b918ffc5b26.png)

**Comment by qchasserieau** [comment]
Super ! 

Quand le champs oneway est défini, je pensais avoir un geojson à géométrie unique dans les inputs / éditable.
ça respecte le mode de fonctionnement initial (en termes d'ajout de nœuds et de découpe de liens) et c'est plus léger.
L'inconvénient est dans le mode carto, pour representer les vitesses  des inputs par exemple : on ne peut pas basculer vers une vue à deux géométrie.
Mais je pense que c'est un bon compromis.

Un mode de fonctionnement viable est de dédoubler les géométries en début de modélisation dans Quetzal et les laisser dédoublées jusque dans les outputs.

On peut en parler de vive voix quand tu veux

**Comment by sboivinsystra** [comment]
pour les champs _r, il reste a 
0) ajouter champs _r au liens oneway=true et les afficher lors de l'edition d'un rLink
1) edit group: editer les _r aussi.
2) quand on passe de oneway 1 a 0 = > on copie les attributs du liens vers les _r
3) laisser le champs time_r
4) calculer time_r et length_r
5) loader les liens avec des _r comme il faut
6) a l'export, ou lorsqu'on passe de 1 a 0, supprimer les champs _r

**Comment by sboivinsystra** [comment]
oneway field 0 or 1. 0 means oneway.

- when field is 0, corresponding _r attributes are created on the links. copying the data (ex: speed = speed_r)
- when a group is edited. the corresponding _r value are also edited (ex: changing speed =120 on every motorway will pu speed_r =120 also.)
- when a link onway is changed from 1 to 0, the _r attributes are added and copy from the original one (ex: speed = speed_r).
- when a link onway is changed from 0 to a, the _r attributes are deleted
- when a group oneway is change from 1 to 0, the _r attributes are added and copy from the original one (ex: speed = speed_r) only for links that were onewal=1 (if a link was already oneway=0, its value will not be overwrite).
- you can load files with _r fields and it will work (if oneway is also provided)
- moving a node or creating a node update both length, length_r, time and time_r
