### ISSUE TITLE
popup does not pop up when hovering polygons in result map

### ISSUE THREAD

**Issue by qchasserieau** [systragroup/quetzal-network-editor#332]

**Comment by sboivinsystra** [comment]
cetait voulu. les popup etaient tres weird sur polygon de souvenir. on pourrait discuter du comportement voulu

**Comment by sboivinsystra** [comment]
added popup on zone centroid. change when hovering a new zone. can disapear with a click outside de layer

**Comment by qchasserieau** [comment]
aweille, c'est toujours weird effectivement...
Pas sûr qu'on veuille ça.
