### ISSUE TITLE
Delete outputs

### ISSUE THREAD

**Issue by siforf564** [systragroup/quetzal-network-editor#341]
When we launch a simulation, outputs should be deleted on S3. Model may not produce the same file again and ols file are hanging on...

**Comment by sboivinsystra** [comment]
should the back do it?
If the front do it. the results will be deleted even if the simulation fail. also, the Map result page will be empty when the simulation is running

**Comment by sboivinsystra** [comment]
We do want the front to do it. at start. delete all outputs

**Comment by sboivinsystra** [comment]
as of today. you can upload output files from the frontend. should the front delete the output? because i think we want to delete the Quetzal model generated output, not any others...

**Comment by sboivinsystra** [comment]
delete all outputs on s3 when  a simulation is launch. this will not delete the outputs already in memory. so you can still viz them in result page.

will be in 4.9.f
