### ISSUE TITLE
Update Quetzal Dockerization README

### ISSUE THREAD

**Issue by siforf564** [systragroup/quetzal-network-editor#357]

**Comment by sboivinsystra** [comment]
sur quetzal. dans la branche docker. dossier docker.

**Comment by sboivinsystra** [comment]
Dans quetzal-config on a cognito_group_access.json qui map les noms des groupes aux nom des buckets.

donc. pour un nouveau modele, il faut:

créer un S3 bucket avec les CORS appropriées ( ex: quetzal-montreal )
créer une policy ( ex: s3_read_put_quetzal_montreal )
créer un IAM role ( ex: Cognito_quetzal_pool_quetzal_montreal )
4.1) attacher la policy et la policy s3_read_quetzal_config.
4.2) attacher la policy s3_read_quetzal_config.
créer un user group cognito ( ex: quetzal_montreal )
mettre les user dans le group
mettre à jour cognito_group_access.json dans s3://quetzal-config ( ex: quetzal_montreal: [ "quetzal-montreal"] )
Seulement l'étape 4.2 et 7 sont nouvelles par rapport à avant.

**Comment by siforf564** [comment]
https://github.com/systragroup/quetzal/blob/docker/docker/README.md
