### ISSUE TITLE
highlight outputs that are visible with the layer module (in the inport vue)

### ISSUE THREAD

**Issue by qchasserieau** [systragroup/quetzal-network-editor#378]

**Comment by qchasserieau** [comment]
for instance : add the layer icon next to the output name

**Comment by sboivinsystra** [comment]
![image](https://github.com/systragroup/quetzal-network-editor/assets/79281989/d88d10f7-39a4-4024-94fe-6e66511e47c9)

**Comment by sboivinsystra** [comment]
there is also a tooltip "viewable in results"
