### ISSUE TITLE
OSM import of cycle network in grand Tokio (or Montreal)

### ISSUE THREAD

**Issue by qchasserieau** [systragroup/quetzal-network-editor#386]
Yeah, it is too much for a single Overpass API request.
Still, we want it.

![image](https://github.com/systragroup/quetzal-network-editor/assets/32388980/f471caa1-8d8c-4529-a05d-220dd5f11471)

**Comment by sboivinsystra** [comment]
add try except.

this function was averaging lanes tag as ' 1;2 ' . however, sometime. its not 2 number but some random string...

**Comment by sboivinsystra** [comment]
wrong git
