### ISSUE TITLE
Origin Destination Editor

### ISSUE THREAD

**Issue by qchasserieau** [systragroup/quetzal-network-editor#390]
How about we add a panel in the edition map to edit od.geojson.
We just want to draw arrows and edit the fields and use the filters and colours like in PT and road.
Then it can be displayed in the output map with color analysis and stuff 
And it is placed either in inputs/od.geojson or inputs/od/od.geojson where we may want to add inputs/od/demand.geojson at some point

**Comment by sboivinsystra** [comment]
4.9.b
