### ISSUE TITLE
Remove "scenario" parameters in step model inputs

### ISSUE THREAD

**Issue by siforf564** [systragroup/quetzal-network-editor#393]
We should let the model choose its default scenrio to use

https://github.com/systragroup/quetzal-network-editor/blob/1796017be705e76451015cbae50c06351fe5c209/src/store/api/run.js#L134C14-L134C30

**Comment by sboivinsystra** [comment]
will this break the dockers?

**Comment by siforf564** [comment]
Not supposed to. As it is not used in main.py and notebook have default values for scenario

**Comment by sboivinsystra** [comment]
4.8.c
