### ISSUE TITLE
Matrix road caster does not seem to work with cyclops network in singapore

### ISSUE THREAD

**Issue by qchasserieau** [systragroup/quetzal-network-editor#401]
Is it because of the _one geometry for both directions_ format ?

**Comment by qchasserieau** [comment]
![image](https://github.com/systragroup/quetzal-network-editor/assets/32388980/59946d40-3f45-441e-98f5-8a69b1e096c1)

**Comment by sboivinsystra** [comment]
even tho the polygon did not intercept, I suspect that HERE rounds the coords to some precision. And rounding them could duplicate them (first point of the circle == last point).

It could also be the Docker. I had some difference in the last digit between jupyter and docker...

anyway , I round to 5 digit and drop duplicates.
