### ISSUE TITLE
Update model to new Quenedi Files structure

### ISSUE THREAD

**Issue by sboivinsystra** [systragroup/quetzal-network-editor#406]
- quetzal-test ✅
- quetzal-paris ✅
- quetzal-cyclops ✅
- quetzal-hfr ✅
- quetzal-paname ❌ (deleted)
- quetzal-toronto
- quetzal-auckland

**Comment by sboivinsystra** [comment]
I can do the infra (delete everything and recreate it with terraform).
in any case, we should recreate the infra with terraform for every model to have something sustainable.

To delete:
- [ ] ECR
- [ ] S3
- [ ] lambda
- [ ] step function
- [ ] policies (for the iam role, lambda and step function
- [ ] role
- [ ] cloudWatch log group
to update:
Cognito group and policies in appropriate Group.

**Comment by siforf564** [comment]
quetzal-toronto ✅
