### ISSUE TITLE
hex Colors in Geojsons and colormaps

### ISSUE THREAD

**Issue by qchasserieau** [systragroup/quetzal-network-editor#424]
- If there is a color field in a geojson with hex codes : make it possible to use as is by selecting it (color x width relation to be designed though )
- add random colormaps
- if their is a string field enable coloring by that field 
(for example you can have a mapping str->int and then user can use random colormap)

**Comment by sboivinsystra** [comment]
point 2 and 3  in 4.10.m.

**Comment by safth** [comment]
point 1 in 4.10.n for the color.

There is still no way to select a width and the minWidth is used for all links. i'm not sure how I can do both at the moment...
