### ISSUE TITLE
Import GTFS of translink vancouver

### ISSUE THREAD

**Issue by qchasserieau** [systragroup/quetzal-network-editor#435]
![image](https://github.com/systragroup/quetzal-network-editor/assets/32388980/3a6bd691-89dc-468e-98b1-a4ca68846ad6)
There is an issue with the GTFS maybe the importer need a workaround for cases like that ?

**Comment by sboivinsystra** [comment]
jài corrigé pour renvoyé un geojson vide si il n'y a rien. par contre. je trouve le comportement feed.restrict() louche...


![image](https://github.com/systragroup/quetzal-network-editor/assets/79281989/90332a7e-4e5a-4ec1-9c11-ab208d3be549)

**Comment by sboivinsystra** [comment]
fixed in quetzal.
