### ISSUE TITLE
Stop logging out of a scenario when «delete all» in the import menu

### ISSUE THREAD

**Issue by qchasserieau** [systragroup/quetzal-network-editor#460]
![image](https://github.com/systragroup/quetzal-network-editor/assets/32388980/e51f859e-cf23-4092-b2d9-82e20ad7a224)
we may want to delete all from a scen and import a fresh zip

**Comment by sboivinsystra** [comment]
maybe another button?  @qchasserieau 
2 cases: 
  - a new scenario not on the cloud (like refreshing the page)
  - erase all on a loaded scenario.

there is no way to exit a loaded snenario except this. we could also reclick on the loaded Scen to unload it.

**Comment by sboivinsystra** [comment]
5.0.x

empty all button will not unload a scenario.

clicking on the loaded scenario will empty all and unload scenario.
