### ISSUE TITLE
Sauvegarde préréglage avec nombreux filtres ne marche pas 

### ISSUE THREAD

**Issue by martinlary** [systragroup/quetzal-network-editor#463]
Exemple ici 
![image](https://github.com/systragroup/quetzal-network-editor/assets/66305574/d405044d-ca96-4847-9c15-54d148ac3d38)

**Comment by sboivinsystra** [comment]
@martinlary quest-ce qui ne marche pas? ca crash ou les filtres ne sont pas sauvegardé?

**Comment by sboivinsystra** [comment]
j'ai corrigé un petit bug qui faisait en sorte que la sauvegarde etait tres lente et pouvais faire crash l'app

5.0.v
