### ISSUE TITLE
Ensure Sqeuential Link Sequence

### ISSUE THREAD

**Issue by siforf564** [systragroup/quetzal-network-editor#492]
Link Sequence does not seems to stay sequential.

Exemple in quetzal-hfr >> BUG >> ott-tor-omni_oak_0
where link_sequence starts at 3 and jump from 4 to 6. 

This trip have been created from a copy and by removing nodes which may have led to this problem

**Comment by sboivinsystra** [comment]
I don't fully understand how this happen. 

However. editor_links are now sorted (with link sequence) when entering edition mode. non sorted links could have created the problem as deleting nodes assume that the links are sorted when changing link_sequence.

Cloning trips also assumed it was sorted which was problematic.

note: cloning trips will start at link_sequence=0 and increase by 1

**Comment by sboivinsystra** [comment]
5.2.f
