### ISSUE TITLE
Bug in copy (w/o reverse)

### ISSUE THREAD

**Issue by siforf564** [systragroup/quetzal-network-editor#493]
When making a copy of a trip without reversing the trip, the detection of the first and last node seems to be broken.

exemple: quetzal-hfr >> BUG >> "ott-tor-omni_0 copy"

In this exmple, the first and last node (which are available for extension of the trip) are Toronto (Pearson) and Peterborough instead of Ottawa and Oakville

**Comment by sboivinsystra** [comment]
5.2.f
