### ISSUE TITLE
Scheduling Editor

### ISSUE THREAD

**Issue by siforf564** [systragroup/quetzal-network-editor#500]
**Implementation of the scheduling fonctionnality**

Currently, each links have a fix time/speed and a headway. Sequence of those links forms a trip with unique trip_id.
We would like to be able to switch to a scheduling format where a trip can be repeated a variable intervals.

**Here are some specification of the fonctionnality:**
- When creating a new trip, it is by default a headway trip. It is only afterward that you can switch to a schedulling based trip.
- When a trip is switch to a schedulling based trip, it is called a ttrip (temporal trip)
- When a trip is switch to a ttrip, time, speed and heaway collumns of each link are disabled. They are replaced by columns of departure and arrival. 
- You switch a trip to ttrip by entering the scheduling dialog (see draft below) and adding new ttrip (temporal trip). You can add as many as you want.
- ttrips arrival and departure schedule can then be edited individualy in the schedulling dialog

- scroll on the schedule = time zoom
- scrolle outside of the schdule = vertical scroll (stations)

**Comment by siforf564** [comment]
- Add title for departures arrivals
- add a selector for node label
- Implement delete function
- When hovering a schedule input field, highlight the corresponding node in the chart

**Comment by siforf564** [comment]
- When hovering a schedule input field, highlight the corresponding node in the chart
- Bug when reversing

**Comment by sboivinsystra** [comment]
Can now Add nodes, Delete nodes and Draw (upward downward)

**Comment by sboivinsystra** [comment]
disabled  speed edition when schedule mode.
