### ISSUE TITLE
Mapmatching : add options to add PT indicators to road network.

### ISSUE THREAD

**Issue by qchasserieau** [systragroup/quetzal-network-editor#540]
- number of trips & number of lines
- cumulative frequency or combined headway = 1 / (sum of 1/headway_of_each_line)
_- average speed of the TC, weighted by number of trips of frequency | this will require a reconstruction algorithm for the times are always weird in GTFS_

**Comment by sboivinsystra** [comment]
Last item move to :

https://github.com/systragroup/quetzal-network-editor/issues/539
