### ISSUE TITLE
Handle category specific information

### ISSUE THREAD

**Issue by qchasserieau** [systragroup/quetzal-network-editor#551]
Currently, their is a header with model info.
We could have the same for each category.
For each category, {"category":"aggregation", **"info": "this is my category info"**, "params":...}

**Comment by sboivinsystra** [comment]
![Screenshot from 2024-09-24 13-13-47](https://github.com/user-attachments/assets/dbd0b1d1-9fde-45d6-b0e5-48bb153efd04)
