### ISSUE TITLE
edit parameters hints inplace

### ISSUE THREAD

**Issue by sboivinsystra** [systragroup/quetzal-network-editor#554]
can replace the hint with v-slot:details

something like that

<template v-slot:details>
    <input
      v-show="showHint"
      v-model="item.hint"
    >
  </template>

**Comment by qchasserieau** [comment]
In terms of UI: the ? togle is something we could keep to hide or show.
Then : double click on the hint to open the edition, hit **enter** to close and save to the app.
 and then same behaviour to save to json or s3 as for the parameters themselves

**Comment by sboivinsystra** [comment]
6.1.b

enter and double click.
