### ISSUE TITLE
Permettre d'annuler une action d'édition du réseau routier : 

### ISSUE THREAD

**Issue by qchasserieau** [systragroup/quetzal-network-editor#563]
Voici un exemple où on aurait des sessions d'édition, qu'on peut annuler.
On pourrait avoir le même genre de menu que pour les TC 
Avec EDIT network en bas
![image](https://github.com/user-attachments/assets/68263cdb-d852-4a04-aaa4-893e47f296ee)
Puis quand on commence à éditer on peut valider ou annuler
![image](https://github.com/user-attachments/assets/1945a46e-cbff-42d7-840a-58258d4bc978)
ça nécéssite de copier le réseau pour référence quand on commence l'édition, peut être un peu lourd mais bon....

**Comment by sboivinsystra** [comment]
6.1.h
