### ISSUE TITLE
Mouse Over Link

### ISSUE THREAD

**Issue by qchasserieau** [systragroup/quetzal-network-editor#93]
Quand on survole un lien : afficher le guide des actions disponibles 
- gauche pour ajouter un nœuds
- droit pour les attributs

**Comment by sboivinsystra** [comment]
pas de menu contextuelle.

**Comment by qchasserieau** [comment]
je propose GAUCHE pour ajouter un nœud et DROIT pour les attributs.
Comme ça gauche permet d'ajouter un nœud en bout de ligne ou en milieu de lien
