### ISSUE TITLE
Drag and drop event sequence for the nodes

### ISSUE THREAD

**Issue by qchasserieau** [systragroup/quetzal-network-editor#94]
Depuis le mode édition on doit pouvoir déplacer tous les nœuds :
Quand on hover : grossir le nœud
Mouse Down : «saisir le nœud»
Mouse Leave : quand on sort de l'image du gros nœud : on passe en mode «déplacer le nœud»
Mouse Up (quand on est en mode déplacer le nœud): on valide la nouvelle position du nœud
Mouse Up (quand on est en mode saisi): désactiver le mode saisi

**Comment by sboivinsystra** [comment]
click gauche on fait rien
