### ISSUE TITLE
new Left Panel

### ISSUE THREAD

**Issue by sboivinsystra** [systragroup/quetzal-network-editor#96]
enlever les actions.

mettre un edit line properties dans le menu deroullant.

mettre des "fa-solid fa-table-list"

**Comment by sboivinsystra** [comment]
pour ne pas avoir trop de piton. je suggere:
1)clique droit sur le crayon 
2)clique sur le text pour faire le crayon et remplacer le crayon.
3) clique droit crayon ou texte = edit line et gauche edit properties.

dans tout les cas, avoir un petit popup qui explique

**Comment by siforf564** [comment]
@sboivinsystra Les 3 boutons a droite du texte ne me choque pas. Je sais pas si je comprends mal ta proposition, mais ça me semble un peu compliquer pour rien. Tout d'abord je crois que tu te trompe entre la gauche et la droite.

**Comment by sboivinsystra** [comment]
@siforf564 pour 3) jai inversé gauche et droite oui.
cest pas parfait, mais tu peux voir que ca prend beaucoup d'espace

![Screen Shot 2022-09-19 at 9 55 10 AM](https://user-images.githubusercontent.com/79281989/191034061-131154ea-abbe-4522-8f2c-5161eb58b44b.png)

**Comment by siforf564** [comment]
Ouais ben la poubelle prend 2x fois trop d'espace
